### ISSUE TITLE
Can't change the active background color

### ISSUE THREAD

**Issue by rca-tiago-salomon** [manishjanky/ngx-sortable#2]
Isn't possible to change the blue background color of active list. Has a !important in your css code, please remove this.

Thanks.

**Comment by manishjanky** [comment]
Let me have a look. Will update soon.

**Comment by manishjanky** [comment]
So sorry for the late response. Did you try using the `!important` flag that should do the trick.

**Comment by kentonbmax** [comment]
I have this same issue. I believe its because there is a hover or active class that gets applied which has important set on it. See the image below and I would recommend removing '!important' from which ever style sets the color on active. 
![image](https://user-images.githubusercontent.com/15804484/56388627-79366300-61f5-11e9-8356-4de0a77598d6.png)

**Comment by nakulchauhan** [comment]
Hi 
Any update on this?

**Comment by manishjanky** [comment]
Please update to latest version
